# Generated by Django 3.0.4 on 2020-08-08 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assesment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assesment_name', models.CharField(max_length=100, null=True)),
                ('assesment_subject', models.CharField(max_length=100, null=True)),
                ('assesment_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100, null=True)),
                ('school_region', models.CharField(max_length=100, null=True)),
                ('school_password', models.CharField(max_length=100)),
                ('school_email', models.EmailField(max_length=100, null=True, unique=True)),
                ('school_teachers_count', models.CharField(max_length=100, null=True)),
                ('school_classroom_count', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, null=True)),
                ('student_school', models.CharField(max_length=100, null=True)),
                ('student_score', models.CharField(max_length=100, null=True)),
                ('student_grade', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100, null=True)),
                ('teacher_email', models.EmailField(max_length=100, null=True, unique=True)),
                ('teacher_password', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(max_length=100, null=True)),
                ('training_subject', models.CharField(max_length=100, null=True)),
                ('training_date', models.DateField()),
                ('training_hours', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Training_Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KEF_App.Teacher')),
                ('training_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KEF_App.Training')),
            ],
        ),
        migrations.CreateModel(
            name='School_Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KEF_App.School')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KEF_App.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Assesment_Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_score', models.CharField(max_length=100, null=True)),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KEF_App.Teacher')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KEF_App.Assesment')),
            ],
        ),
    ]
