# Generated by Django 3.1 on 2020-08-08 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KEF_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_title', models.CharField(max_length=100)),
                ('query_text', models.CharField(max_length=100)),
                ('query_comment', models.CharField(max_length=100)),
                ('query_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KEF_App.teacher')),
            ],
            options={
                'verbose_name_plural': 'Teacher_Queries',
            },
        ),
    ]
