# Generated by Django 3.1 on 2020-08-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KEF_App', '0003_remove_teacher_query_query_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_query',
            name='query_comment',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
