# Generated by Django 3.1 on 2020-08-09 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KEF_App', '0004_auto_20200809_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='assesment',
            name='assesment_link',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='school_teacher',
            name='school_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='KEF_App.school'),
            preserve_default=False,
        ),
    ]
